baseurl = "/"
defaultContentLanguage = "en"
disableKinds = ["RSS"]
enableRobotsTXT = true
languageCode = "en-us"
theme = "prologue"
title = "Jer Keller"
[params]
copyright = "2018 Jer Keller"
description = "custom drums for your project"
name = "Jer Keller"
[[params.portfolio1]]
alt = "Screenshot of Jer's ReverbNation gig calendar"
source = ""
title = "Gig Calendar"
url = "https://www.reverbnation.com/jerkeller/shows"
[[params.portfolio2]]
alt = "Screenshot of website for The Dizzys' band"
source = "img/dizzys-screenshot.jpg"
title = "The Dizzys"
url = "http://thedizzysband.com"
[[params.portfolio3]]
alt = ""
source = "#"
title = "His Place Church"
url = "#"
[[params.testimonial1]]
alt = "Photo of Joe Nurre looking into the camera. Copyright Joe Nurre https://www.facebook.com/joenurreartist"
source = "img/joe.jpg"
testimonial = "Having played with Jer off and on for over 10 years, in the end if you need a quality/lasting product, you go to him. Not only is he fluent in his work on the drums, his ear is finely tuned having spent much of his time behind a mixing console working on projects ranging from death metal to mainstream rock, its a guarantee you wont be dissapointed."
author = "Joe Nurre"
authordesc = "Shaded Enmity, Jeff Loomis"
[[params.testimonial2]]
alt = ""
source = "img/user.svg"
testimonial = "Placeholder testimonial 2 text. Replace this with a real testimonial later"
author = "Author's Name"
authordesc = "Description of the author's position"
[[params.social]]
icon = "twitter"
link = "https://twitter.com/_audiosyncrasy"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "https://www.facebook.com/jerkeller"
medium = "facebook"
[[params.social]]
icon = "envelope"
link = "mailto:jer@jerkeller.com"
medium = "email"
