baseurl = "/"
defaultContentLanguage = "en"
disableKinds = ["RSS"]
enableRobotsTXT = true
languageCode = "en-us"
theme = "prologue"
title = "Jer Keller"
[params]
copyright = "2018 Jer Keller"
description = "custom drums for your project"
name = "Jer Keller"
[[params.portfolio1]]
alt = ""
source = "#"
title = "Music Project"
url = "#"
[[params.portfolio2]]
alt = "Screenshot of website for The Dizzys' band"
source = "img/dizzys-screenshot.jpg"
title = "The Dizzys"
url = "http://thedizzysband.com"
[[params.portfolio3]]
alt = ""
source = "#"
title = "His Place Church"
url = "#"
[[params.social]]
icon = "twitter"
link = "https://twitter.com/_audiosyncrasy"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "https://www.facebook.com/jerkeller"
medium = "facebook"
[[params.social]]
icon = "github"
link = "https://github.com/Audiosyncrasy"
medium = "github"
[[params.social]]
icon = "envelope"
link = "mailto:jer@jerkeller.com"
medium = "email"
