baseurl = "/"
defaultContentLanguage = "en"
disableKinds = ["RSS"]
enableRobotsTXT = true
languageCode = "en-us"
theme = "prologue"
title = "Jer Keller"
[params]
copyright = "2018 Jer Keller"
description = "delivering custom web-based solutions in a personalized customer experience"
name = "Jer Keller"
[[params.portfolio1]]
alt = "Screenshot of Todd's Auto Service's website"
desc = "The client wanted a simple, fast-loading web site that provides contact information for Todd's Auto Service and a description of what services they offer. Site features include responsive design that scales based on the device size, a Testimonials section that includes Facebook reviews, and an interactive map on the Contact page."
source = "img/tas-screenshot.jpg"
title = "Todd's Auto Service"
url = "https://www.toddsautoservice.com"
[[params.portfolio2]]
alt = "Screenshot of the Gen of Eve Photography website"
desc = "I built this site for a freelance photographer who wanted to showcase her work and start building a web-presence through regular blog posts. Built from scratch using WordPress, this site features a robust photo gallery, a blog page, and an interface that allows her to refresh content on her website as her business grows and changes."
source = "img/goep-screenshot.jpg"
title = "Gen of Eve Photography"
url = "https://genofevephotography.com/"
[[params.portfolio3]]
alt = "Screenshot of website for The Dizzy's band"
desc = "The goal with The Dizzys' web site was to provide a fast, responsive place for fans to connect with the band. The Shows page integrates with the band's Bandsintown account. When members add a show on Bandsintown, the site updates automatically, avoiding the need to update the website directly. In addition, there is a contact page that allows fans and booking agents to connect with the band via email."
source = "img/dizzys-screenshot.jpg"
title = "The Dizzys Band"
url = "http://thedizzysband.com"
[[params.social]]
icon = "twitter"
link = "https://twitter.com/_audiosyncrasy"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "https://www.facebook.com/jerkeller"
medium = "facebook"
[[params.social]]
icon = "github"
link = "https://github.com/Audiosyncrasy"
medium = "github"
[[params.social]]
icon = "linkedin"
link = "https://www.linkedin.com/in/jeremiah-keller-62a94011b"
medium = "linkedin"
[[params.social]]
icon = "envelope"
link = "mailto:jer@jerkeller.com"
medium = "email"
